apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: default-client-common
objects:
- apiVersion: v1
  kind: User
  metadata:
    labels:
      client: ${CLIENT}
    name: ${USER}
parameters:
  - name: CLIENT
  - name: USER

